# Generated by Django 5.2 on 2025-06-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('pdf_certificado_sanitario', models.FileField(blank=True, null=True, upload_to='proveedores/certificados/')),
            ],
        ),
    ]
