# Generated by Django 5.2 on 2025-06-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='pdf_certificado_sanitario',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores'),
        ),
    ]
