# Generated by Django 5.2 on 2025-06-12 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alimentos', '0001_initial'),
        ('Proveedor', '0002_alter_proveedor_pdf_certificado_sanitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('pdf_factura', models.FileField(blank=True, null=True, upload_to='Lotes')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Alimentos.alimento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Proveedor.proveedor')),
            ],
        ),
    ]
